name: build-push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  tags:
      - v*

  workflow_dispatch:

jobs:
  egg-standalone-node:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      
      - name: Build Image
        run: ./scripts/build-standalone-docker.sh
      
      - name: Install docker-slim
        run: curl -sL https://raw.githubusercontent.com/docker-slim/docker-slim/master/scripts/install-dockerslim.sh | sudo -E bash -
      
      - name: Slim down the Image
        run: docker-slim build --target webb-tools/egg-standalone-node --http-probe-off --entrypoint egg-standalone-node
      
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/egg-standalone-node

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `edge` tag convention
          [ "$VERSION" == "main" ] && VERSION=edge

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag webb-tools/egg-standalone-node.slim $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  egg-parachain-node:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      
      - name: Build Image
        run: ./scripts/build-parachain-docker.sh
      
      - name: Install docker-slim
        run: curl -sL https://raw.githubusercontent.com/docker-slim/docker-slim/master/scripts/install-dockerslim.sh | sudo -E bash -
      
      - name: Slim down the Image
        run: docker-slim build --target webb-tools/egg-standalone-node --http-probe-off --entrypoint egg-collator
      
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/egg-collator

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `edge` tag convention
          [ "$VERSION" == "main" ] && VERSION=edge

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag webb-tools/egg-collator.slim $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
