[package]
name = "primitives-ext"
version = "0.1.0"
authors = { workspace = true }
edition = "2021"
license = "GPL-3.0-only"
repository = { workspace = true }

[dependencies]
# Moonbeam
evm-tracing-events = { workspace = true }

# Substrate
parity-scale-codec = { workspace = true }
sp-runtime-interface = { workspace = true }
sp-std = { workspace = true }

[features]
default = ["std"]
std = [
  "evm-tracing-events/std",
  "parity-scale-codec/std",
  "sp-runtime-interface/std",
  "sp-std/std",
]
