# LOKI LOG CONFIGURATION
#
# The below configuration outlines a simple Loki setup that will spin up a server on localhost:3100 and scrape the logs which can then 
# be viewed, queried and visualized using Grafana. 
# 
# In order to log events with Grafana Loki, download and install both Promtail and Loki.
#
# - Loki is the logging engine.
# - Promtail sends logs to Loki.
# 
# There are many other config options for Loki, and you can read more about Loki configuration 
# at: https://grafana.com/docs/loki/latest/configuration/
#
# For an in-depth guide on how to install Loki please follow: https://grafana.com/docs/loki/latest/installation/

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 0

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h


storage_config:
  boltdb:
    directory: /data/loki/index

  filesystem:
    directory: /data/loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0