// This file is part of Tangle.
// Copyright (C) 2022-2025 Tangle Foundation.
//
// Tangle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Tangle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Tangle.  If not, see <http://www.gnu.org/licenses/>.


//! Autogenerated weights for `pallet_rewards`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 50.0.0
//! DATE: 2025-11-18, STEPS: `10`, REPEAT: `2`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `192.168.0.101`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("chain_spec.json")`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --chain=chain_spec.json
// --pallet=pallet_rewards
// --extrinsic=*
// --steps=10
// --repeat=2
// --template=./.maintain/frame-weights-template.hbs
// --output=./pallets/rewards/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_rewards`.
pub trait WeightInfo {
	fn claim_rewards() -> Weight;
	fn update_vault_reward_config() -> Weight;
	fn claim_rewards_other() -> Weight;
	fn manage_asset_reward_vault() -> Weight;
	fn create_reward_vault() -> Weight;
	fn update_decay_config() -> Weight;
	fn update_apy_blocks() -> Weight;
	fn claim_delegator_rewards() -> Weight;
	fn set_vault_metadata() -> Weight;
	fn remove_vault_metadata() -> Weight;
}

/// Weights for `pallet_rewards` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Rewards::PendingOperatorRewards` (r:1 w:1)
	/// Proof: `Rewards::PendingOperatorRewards` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `432`
		//  Estimated: `6196`
		// Minimum execution time: 40_000_000 picoseconds.
		Weight::from_parts(41_000_000, 6196)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Rewards::RewardConfigStorage` (r:1 w:1)
	/// Proof: `Rewards::RewardConfigStorage` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_vault_reward_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `231`
		//  Estimated: `3696`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(8_000_000, 3696)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Rewards::AssetLookupRewardVaults` (r:1 w:0)
	/// Proof: `Rewards::AssetLookupRewardVaults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::RewardConfigStorage` (r:1 w:0)
	/// Proof: `Rewards::RewardConfigStorage` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::TotalRewardVaultScore` (r:1 w:0)
	/// Proof: `Rewards::TotalRewardVaultScore` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::UserClaimedReward` (r:1 w:1)
	/// Proof: `Rewards::UserClaimedReward` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::TotalRewardVaultDeposit` (r:1 w:0)
	/// Proof: `Rewards::TotalRewardVaultDeposit` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::DecayStartPeriod` (r:1 w:0)
	/// Proof: `Rewards::DecayStartPeriod` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::ApyBlocks` (r:1 w:0)
	/// Proof: `Rewards::ApyBlocks` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::RewardVaultsPotAccount` (r:1 w:0)
	/// Proof: `Rewards::RewardVaultsPotAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn claim_rewards_other() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `969`
		//  Estimated: `4434`
		// Minimum execution time: 31_000_000 picoseconds.
		Weight::from_parts(31_000_000, 4434)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Rewards::AssetLookupRewardVaults` (r:1 w:1)
	/// Proof: `Rewards::AssetLookupRewardVaults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::RewardVaults` (r:1 w:1)
	/// Proof: `Rewards::RewardVaults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn manage_asset_reward_vault() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `244`
		//  Estimated: `3709`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(11_000_000, 3709)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Rewards::RewardConfigStorage` (r:1 w:1)
	/// Proof: `Rewards::RewardConfigStorage` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::RewardVaultsPotAccount` (r:1 w:1)
	/// Proof: `Rewards::RewardVaultsPotAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_reward_vault() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3541`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(9_000_000, 3541)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Rewards::DecayRate` (r:0 w:1)
	/// Proof: `Rewards::DecayRate` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::DecayStartPeriod` (r:0 w:1)
	/// Proof: `Rewards::DecayStartPeriod` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn update_decay_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(4_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Rewards::ApyBlocks` (r:0 w:1)
	/// Proof: `Rewards::ApyBlocks` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn update_apy_blocks() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(4_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Rewards::DelegatorRewardDebts` (r:1 w:1)
	/// Proof: `Rewards::DelegatorRewardDebts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::OperatorRewardPools` (r:1 w:0)
	/// Proof: `Rewards::OperatorRewardPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim_delegator_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `547`
		//  Estimated: `6196`
		// Minimum execution time: 57_000_000 picoseconds.
		Weight::from_parts(64_000_000, 6196)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Rewards::VaultMetadataStore` (r:0 w:1)
	/// Proof: `Rewards::VaultMetadataStore` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_vault_metadata() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(7_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Rewards::VaultMetadataStore` (r:1 w:1)
	/// Proof: `Rewards::VaultMetadataStore` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_vault_metadata() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `153`
		//  Estimated: `3618`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(8_000_000, 3618)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Rewards::PendingOperatorRewards` (r:1 w:1)
	/// Proof: `Rewards::PendingOperatorRewards` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `432`
		//  Estimated: `6196`
		// Minimum execution time: 40_000_000 picoseconds.
		Weight::from_parts(41_000_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Rewards::RewardConfigStorage` (r:1 w:1)
	/// Proof: `Rewards::RewardConfigStorage` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_vault_reward_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `231`
		//  Estimated: `3696`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(8_000_000, 3696)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Rewards::AssetLookupRewardVaults` (r:1 w:0)
	/// Proof: `Rewards::AssetLookupRewardVaults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::RewardConfigStorage` (r:1 w:0)
	/// Proof: `Rewards::RewardConfigStorage` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::TotalRewardVaultScore` (r:1 w:0)
	/// Proof: `Rewards::TotalRewardVaultScore` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::UserClaimedReward` (r:1 w:1)
	/// Proof: `Rewards::UserClaimedReward` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::TotalRewardVaultDeposit` (r:1 w:0)
	/// Proof: `Rewards::TotalRewardVaultDeposit` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::DecayStartPeriod` (r:1 w:0)
	/// Proof: `Rewards::DecayStartPeriod` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::ApyBlocks` (r:1 w:0)
	/// Proof: `Rewards::ApyBlocks` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::RewardVaultsPotAccount` (r:1 w:0)
	/// Proof: `Rewards::RewardVaultsPotAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn claim_rewards_other() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `969`
		//  Estimated: `4434`
		// Minimum execution time: 31_000_000 picoseconds.
		Weight::from_parts(31_000_000, 4434)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Rewards::AssetLookupRewardVaults` (r:1 w:1)
	/// Proof: `Rewards::AssetLookupRewardVaults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::RewardVaults` (r:1 w:1)
	/// Proof: `Rewards::RewardVaults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn manage_asset_reward_vault() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `244`
		//  Estimated: `3709`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(11_000_000, 3709)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Rewards::RewardConfigStorage` (r:1 w:1)
	/// Proof: `Rewards::RewardConfigStorage` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::RewardVaultsPotAccount` (r:1 w:1)
	/// Proof: `Rewards::RewardVaultsPotAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_reward_vault() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3541`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(9_000_000, 3541)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Rewards::DecayRate` (r:0 w:1)
	/// Proof: `Rewards::DecayRate` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::DecayStartPeriod` (r:0 w:1)
	/// Proof: `Rewards::DecayStartPeriod` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn update_decay_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(4_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Rewards::ApyBlocks` (r:0 w:1)
	/// Proof: `Rewards::ApyBlocks` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn update_apy_blocks() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(4_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Rewards::DelegatorRewardDebts` (r:1 w:1)
	/// Proof: `Rewards::DelegatorRewardDebts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::OperatorRewardPools` (r:1 w:0)
	/// Proof: `Rewards::OperatorRewardPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim_delegator_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `547`
		//  Estimated: `6196`
		// Minimum execution time: 57_000_000 picoseconds.
		Weight::from_parts(64_000_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Rewards::VaultMetadataStore` (r:0 w:1)
	/// Proof: `Rewards::VaultMetadataStore` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_vault_metadata() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(7_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Rewards::VaultMetadataStore` (r:1 w:1)
	/// Proof: `Rewards::VaultMetadataStore` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_vault_metadata() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `153`
		//  Estimated: `3618`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(8_000_000, 3618)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}