# Docker compose file to start tangle parachain collator that connects to tangle testnet

version: "3.7"
services:

  tangle:
    image: ghcr.io/webb-tools/tangle/tangle-parachain:${RELEASE_VERSION}
    command:
      - "--node-key"
      - ${NODE_KEY}
      - "--base-path"
      - ${BASE_PATH}
      - "--chain tangle-dev"
      - "--port"
      - "30333"
      - "--validator"
      - "--bootnodes"
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      - "--rpc-cors"
      - "--prometheus-external"
      - "--" 
      - "--execution wasm"
      - "--name=YOUR-NODE-NAME"  
    ports:
      - "9944:9944"
      - "9615:9615"
      - "9933:9933"
    volumes:
      - ${BASE_PATH}
      - ${CHAINSPEC_PATH}

networks:
  network-a:
  internet: