# Docker compose file to start tangle parachain collator that connects to tangle testnet

version: "3.7"
services:

  tangle:
    image: ghcr.io/webb-tools/tangle/tangle-parachain:${RELEASE_VERSION}
    network_mode: host
    entrypoint: /tangle-parachain
    command:
      - "--chain"
      - "--base-path=/data"
      - "/var/lib/data/arana-alpha.json"
      - "--collator"
      - "--execution wasm"
      - "--wasm-execution compiled"
      - "--prometheus-external"
      - "--name=YOUR-NODE-NAME"
      - "--" 
      - "--execution wasm"
      - "--name=YOUR-NODE-NAME (Relay)"
    ports:
      - "9944:9944"
      - "9615:9615"
      - "9933:9933"
      - "30333:30333"
    volumes:
      - ${CHAINSPEC_PATH}:/var/lib/data/arana-alpha.json