# Docker compose file to start tangle node with all monitoring services
version: '3.7'

services:
  tangle:
    image: ghcr.io/webb-tools/tangle/tangle:main
    network_mode: host
    entrypoint: /tangle
    volumes:
      - "tangle-data:/data"
    command:
      - "--chain=tangle-testnet"
      - "--validator"
      - "--prometheus-external"
      - "--telemetry-url wss://telemetry.polkadot.io/submit/ 0"
    ports:
      - "9944:9944"
      - "9615:9615"
      - "9933:9933"
      - "30333:30333"

  prometheus:
    image: prom/prometheus
    network_mode: host
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    network_mode: host
    restart: always
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  alertmanager:
    image: prom/alertmanager:v0.23.0
    network_mode: host
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - "./alertmanager:/config"
      - alertmanager_data:/data
    command: --config.file=/config/alertmanager.yml --log.level=debug

  loki:
    image: grafana/loki:2.5.0
    network_mode: host
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
  
  promtail:
    image: grafana/promtail:2.5.0
    network_mode: host
    volumes:
      - /root/collator_logs:/var/log
      - ./loki/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

volumes:
  prometheus_data: {}
  alertmanager_data: {}
  grafana_data: {}
  tangle-data: {}