# ALERT MANAGER CONFIGURATION
#
# The below configuration specifies three distinct alert manager setups. 
# 1. Configured for simple web hooks 
# 2. Configured for GMAIL notifications
# 3. Configured for Slack notifications
#
# There are many other options for alert notifications (e.g. Telegram), and you can read more about Alert Manager configuration 
# at: https://prometheus.io/docs/alerting/latest/configuration/
#
# For an in-depth guide on how to setup Alert Manager please follow: https://grafana.com/blog/2020/02/25/step-by-step-guide-to-setting-up-prometheus-alertmanager-with-slack-pagerduty-and-gmail/

# Specify the preferred configuration 

# ********************************************************************************************************************************************
# Alert Manager for Web Hook Notifications   *
# ********************************************************************************************************************************************

global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
- name: 'web.hook'

# ********************************************************************************************************************************************
# Alert Manager for GMAIL Notifications   *
# ********************************************************************************************************************************************

# global:
#  resolve_timeout: 1m

# route:
#  receiver: 'gmail-notifications'

# receivers:
# - name: 'gmail-notifications'
#   email_configs:
#   - to: YOUR_EMAIL
#     from: YOUR_EMAIL
#     smarthost: smtp.gmail.com:587
#     auth_username: YOUR_EMAIL
#     auth_identity: YOUR_EMAIL
#     auth_password: YOUR_APP_PASSWORD
#     send_resolved: true

# ********************************************************************************************************************************************
# Alert Manager for Slack Notifications  *
# ********************************************************************************************************************************************

# global:
#   resolve_timeout: 1m
#   slack_api_url: 'INSERT SLACK API URL'

# route:
#   receiver: 'slack-notifications'

# receivers:
# - name: 'slack-notifications'
#   slack_configs:
#   - channel: '#channel-name'
#     send_resolved: true
#     icon_url: https://avatars3.githubusercontent.com/u/3380462
#     title: |-
#      [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
#      {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
#        {{" "}}(
#        {{- with .CommonLabels.Remove .GroupLabels.Names }}
#          {{- range $index, $label := .SortedPairs -}}
#            {{ if $index }}, {{ end }}
#            {{- $label.Name }}="{{ $label.Value -}}"
#          {{- end }}
#        {{- end -}}
#        )
#      {{- end }}
#     text: >-
#      {{ range .Alerts -}}
#      *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
#      *Description:* {{ .Annotations.description }}
#      *Details:*
#        {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
#        {{ end }}
#      {{ end }}