// This file is part of Tangle.
// Copyright (C) 2022-2025 Tangle Foundation.
//
// Tangle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Tangle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Tangle.  If not, see <http://www.gnu.org/licenses/>.


//! Autogenerated weights for `pallet_multi_asset_delegation`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 50.0.0
//! DATE: 2025-11-18, STEPS: `10`, REPEAT: `2`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `192.168.0.101`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("chain_spec.json")`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --chain=chain_spec.json
// --pallet=pallet_multi_asset_delegation
// --extrinsic=*
// --steps=10
// --repeat=2
// --template=./.maintain/frame-weights-template.hbs
// --output=./pallets/multi-asset-delegation/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_multi_asset_delegation`.
pub trait WeightInfo {
	fn join_operators() -> Weight;
	fn schedule_leave_operators() -> Weight;
	fn cancel_leave_operators() -> Weight;
	fn execute_leave_operators() -> Weight;
	fn operator_bond_more() -> Weight;
	fn schedule_operator_unstake() -> Weight;
	fn execute_operator_unstake() -> Weight;
	fn cancel_operator_unstake() -> Weight;
	fn go_offline() -> Weight;
	fn go_online() -> Weight;
	fn deposit_with_no_evm_address() -> Weight;
	fn deposit_with_evm_address() -> Weight;
	fn schedule_withdraw() -> Weight;
	fn execute_withdraw_with_no_evm_address() -> Weight;
	fn execute_withdraw_with_evm_address() -> Weight;
	fn cancel_withdraw() -> Weight;
	fn delegate() -> Weight;
	fn schedule_delegator_unstake() -> Weight;
	fn execute_delegator_unstake() -> Weight;
	fn cancel_delegator_unstake() -> Weight;
	fn add_blueprint_id() -> Weight;
	fn remove_blueprint_id() -> Weight;
	fn delegate_nomination() -> Weight;
	fn schedule_nomination_unstake() -> Weight;
	fn execute_nomination_unstake() -> Weight;
	fn cancel_nomination_unstake() -> Weight;
}

/// Weights for `pallet_multi_asset_delegation` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn join_operators() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `103`
		//  Estimated: `3568`
		// Minimum execution time: 17_000_000 picoseconds.
		Weight::from_parts(20_000_000, 3568)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::OperatorsProfile` (r:1 w:0)
	/// Proof: `Services::OperatorsProfile` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::CurrentRound` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::CurrentRound` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn schedule_leave_operators() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `306`
		//  Estimated: `3771`
		// Minimum execution time: 13_000_000 picoseconds.
		Weight::from_parts(16_000_000, 3771)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn cancel_leave_operators() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `201`
		//  Estimated: `3666`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(8_000_000, 3666)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::CurrentRound` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::CurrentRound` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn execute_leave_operators() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `201`
		//  Estimated: `3666`
		// Minimum execution time: 17_000_000 picoseconds.
		Weight::from_parts(17_000_000, 3666)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn operator_bond_more() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `197`
		//  Estimated: `3662`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(21_000_000, 3662)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::OperatorsProfile` (r:1 w:0)
	/// Proof: `Services::OperatorsProfile` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::CurrentRound` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::CurrentRound` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn schedule_operator_unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `306`
		//  Estimated: `3771`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(11_000_000, 3771)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::CurrentRound` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::CurrentRound` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn execute_operator_unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `219`
		//  Estimated: `3684`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(20_000_000, 3684)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn cancel_operator_unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `219`
		//  Estimated: `3684`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(8_000_000, 3684)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::OperatorsProfile` (r:1 w:0)
	/// Proof: `Services::OperatorsProfile` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn go_offline() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `306`
		//  Estimated: `3771`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(14_000_000, 3771)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn go_online() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `197`
		//  Estimated: `3662`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(8_000_000, 3662)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Rewards::AssetLookupRewardVaults` (r:1 w:0)
	/// Proof: `Rewards::AssetLookupRewardVaults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn deposit_with_no_evm_address() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `231`
		//  Estimated: `3696`
		// Minimum execution time: 37_000_000 picoseconds.
		Weight::from_parts(38_000_000, 3696)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Rewards::AssetLookupRewardVaults` (r:1 w:0)
	/// Proof: `Rewards::AssetLookupRewardVaults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn deposit_with_evm_address() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `333`
		//  Estimated: `6196`
		// Minimum execution time: 38_000_000 picoseconds.
		Weight::from_parts(40_000_000, 6196)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::CurrentRound` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::CurrentRound` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn schedule_withdraw() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `218`
		//  Estimated: `3683`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 3683)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::CurrentRound` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::CurrentRound` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn execute_withdraw_with_no_evm_address() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `384`
		//  Estimated: `3849`
		// Minimum execution time: 38_000_000 picoseconds.
		Weight::from_parts(39_000_000, 3849)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::CurrentRound` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::CurrentRound` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn execute_withdraw_with_evm_address() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `486`
		//  Estimated: `6196`
		// Minimum execution time: 34_000_000 picoseconds.
		Weight::from_parts(40_000_000, 6196)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn cancel_withdraw() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `244`
		//  Estimated: `3709`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 3709)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::AssetLookupRewardVaults` (r:1 w:0)
	/// Proof: `Rewards::AssetLookupRewardVaults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn delegate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `389`
		//  Estimated: `3854`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(25_000_000, 3854)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::CurrentRound` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::CurrentRound` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn schedule_delegator_unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `317`
		//  Estimated: `3782`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(12_000_000, 3782)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::CurrentRound` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::CurrentRound` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::AssetLookupRewardVaults` (r:1 w:0)
	/// Proof: `Rewards::AssetLookupRewardVaults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn execute_delegator_unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `578`
		//  Estimated: `4043`
		// Minimum execution time: 16_000_000 picoseconds.
		Weight::from_parts(17_000_000, 4043)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn cancel_delegator_unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `385`
		//  Estimated: `3850`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(9_000_000, 3850)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_blueprint_id() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `309`
		//  Estimated: `3774`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(8_000_000, 3774)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_blueprint_id() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `317`
		//  Estimated: `3782`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(50_000_000, 3782)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Staking::Bonded` (r:1 w:0)
	/// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Ledger` (r:1 w:0)
	/// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(1075), added: 3550, mode: `MaxEncodedLen`)
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(949), added: 3424, mode: `MaxEncodedLen`)
	/// Storage: `Rewards::AssetLookupRewardVaults` (r:1 w:0)
	/// Proof: `Rewards::AssetLookupRewardVaults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn delegate_nomination() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1140`
		//  Estimated: `4764`
		// Minimum execution time: 39_000_000 picoseconds.
		Weight::from_parts(40_000_000, 4764)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::CurrentRound` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::CurrentRound` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn schedule_nomination_unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `490`
		//  Estimated: `3955`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(15_000_000, 3955)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::CurrentRound` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::CurrentRound` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::AssetLookupRewardVaults` (r:1 w:0)
	/// Proof: `Rewards::AssetLookupRewardVaults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(949), added: 3424, mode: `MaxEncodedLen`)
	fn execute_nomination_unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1481`
		//  Estimated: `4946`
		// Minimum execution time: 27_000_000 picoseconds.
		Weight::from_parts(28_000_000, 4946)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn cancel_nomination_unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1225`
		//  Estimated: `4690`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(9_000_000, 4690)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn join_operators() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `103`
		//  Estimated: `3568`
		// Minimum execution time: 17_000_000 picoseconds.
		Weight::from_parts(20_000_000, 3568)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::OperatorsProfile` (r:1 w:0)
	/// Proof: `Services::OperatorsProfile` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::CurrentRound` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::CurrentRound` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn schedule_leave_operators() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `306`
		//  Estimated: `3771`
		// Minimum execution time: 13_000_000 picoseconds.
		Weight::from_parts(16_000_000, 3771)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn cancel_leave_operators() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `201`
		//  Estimated: `3666`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(8_000_000, 3666)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::CurrentRound` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::CurrentRound` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn execute_leave_operators() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `201`
		//  Estimated: `3666`
		// Minimum execution time: 17_000_000 picoseconds.
		Weight::from_parts(17_000_000, 3666)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn operator_bond_more() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `197`
		//  Estimated: `3662`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(21_000_000, 3662)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::OperatorsProfile` (r:1 w:0)
	/// Proof: `Services::OperatorsProfile` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::CurrentRound` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::CurrentRound` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn schedule_operator_unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `306`
		//  Estimated: `3771`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(11_000_000, 3771)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::CurrentRound` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::CurrentRound` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn execute_operator_unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `219`
		//  Estimated: `3684`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(20_000_000, 3684)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn cancel_operator_unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `219`
		//  Estimated: `3684`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(8_000_000, 3684)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::OperatorsProfile` (r:1 w:0)
	/// Proof: `Services::OperatorsProfile` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn go_offline() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `306`
		//  Estimated: `3771`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(14_000_000, 3771)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn go_online() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `197`
		//  Estimated: `3662`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(8_000_000, 3662)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Rewards::AssetLookupRewardVaults` (r:1 w:0)
	/// Proof: `Rewards::AssetLookupRewardVaults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn deposit_with_no_evm_address() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `231`
		//  Estimated: `3696`
		// Minimum execution time: 37_000_000 picoseconds.
		Weight::from_parts(38_000_000, 3696)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Rewards::AssetLookupRewardVaults` (r:1 w:0)
	/// Proof: `Rewards::AssetLookupRewardVaults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn deposit_with_evm_address() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `333`
		//  Estimated: `6196`
		// Minimum execution time: 38_000_000 picoseconds.
		Weight::from_parts(40_000_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::CurrentRound` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::CurrentRound` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn schedule_withdraw() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `218`
		//  Estimated: `3683`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 3683)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::CurrentRound` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::CurrentRound` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn execute_withdraw_with_no_evm_address() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `384`
		//  Estimated: `3849`
		// Minimum execution time: 38_000_000 picoseconds.
		Weight::from_parts(39_000_000, 3849)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::CurrentRound` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::CurrentRound` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn execute_withdraw_with_evm_address() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `486`
		//  Estimated: `6196`
		// Minimum execution time: 34_000_000 picoseconds.
		Weight::from_parts(40_000_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn cancel_withdraw() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `244`
		//  Estimated: `3709`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 3709)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::AssetLookupRewardVaults` (r:1 w:0)
	/// Proof: `Rewards::AssetLookupRewardVaults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn delegate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `389`
		//  Estimated: `3854`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(25_000_000, 3854)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::CurrentRound` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::CurrentRound` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn schedule_delegator_unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `317`
		//  Estimated: `3782`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(12_000_000, 3782)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::CurrentRound` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::CurrentRound` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::AssetLookupRewardVaults` (r:1 w:0)
	/// Proof: `Rewards::AssetLookupRewardVaults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn execute_delegator_unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `578`
		//  Estimated: `4043`
		// Minimum execution time: 16_000_000 picoseconds.
		Weight::from_parts(17_000_000, 4043)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn cancel_delegator_unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `385`
		//  Estimated: `3850`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(9_000_000, 3850)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_blueprint_id() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `309`
		//  Estimated: `3774`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(8_000_000, 3774)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_blueprint_id() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `317`
		//  Estimated: `3782`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(50_000_000, 3782)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Staking::Bonded` (r:1 w:0)
	/// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Ledger` (r:1 w:0)
	/// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(1075), added: 3550, mode: `MaxEncodedLen`)
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(949), added: 3424, mode: `MaxEncodedLen`)
	/// Storage: `Rewards::AssetLookupRewardVaults` (r:1 w:0)
	/// Proof: `Rewards::AssetLookupRewardVaults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn delegate_nomination() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1140`
		//  Estimated: `4764`
		// Minimum execution time: 39_000_000 picoseconds.
		Weight::from_parts(40_000_000, 4764)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::CurrentRound` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::CurrentRound` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn schedule_nomination_unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `490`
		//  Estimated: `3955`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(15_000_000, 3955)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::CurrentRound` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::CurrentRound` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::AssetLookupRewardVaults` (r:1 w:0)
	/// Proof: `Rewards::AssetLookupRewardVaults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(949), added: 3424, mode: `MaxEncodedLen`)
	fn execute_nomination_unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1481`
		//  Estimated: `4946`
		// Minimum execution time: 27_000_000 picoseconds.
		Weight::from_parts(28_000_000, 4946)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:1)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn cancel_nomination_unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1225`
		//  Estimated: `4690`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(9_000_000, 4690)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}