[package]
name = "tangle-relayer-gadget-cli"
version = "0.0.1"
authors = ["Webb Developers <dev@webb.tools>", "Shady Khalifa <dev+github@shadykhalifa.me>"]
edition = { workspace = true }
homepage = { workspace = true }
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
repository = { workspace = true }

[dependencies]
clap = { workspace = true }
