// This file is part of Tangle.
// Copyright (C) 2022-2025 Tangle Foundation.
//
// Tangle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Tangle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Tangle.  If not, see <http://www.gnu.org/licenses/>.


//! Autogenerated weights for `pallet_services`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 50.0.0
//! DATE: 2025-11-18, STEPS: `10`, REPEAT: `2`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `192.168.0.101`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("chain_spec.json")`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --chain=chain_spec.json
// --pallet=pallet_services
// --extrinsic=*
// --steps=10
// --repeat=2
// --template=./.maintain/frame-weights-template.hbs
// --output=./pallets/services/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_services`.
pub trait WeightInfo {
	fn create_blueprint() -> Weight;
	fn pre_register() -> Weight;
	fn register() -> Weight;
	fn unregister() -> Weight;
	fn update_rpc_address() -> Weight;
	fn request() -> Weight;
	fn approve() -> Weight;
	fn reject() -> Weight;
	fn terminate() -> Weight;
	fn call() -> Weight;
	fn request_with_signed_price_quotes() -> Weight;
	fn submit_result() -> Weight;
	fn heartbeat() -> Weight;
	fn slash() -> Weight;
	fn dispute() -> Weight;
	fn update_master_blueprint_service_manager() -> Weight;
	fn update_default_heartbeat_threshold() -> Weight;
	fn update_default_heartbeat_interval() -> Weight;
	fn update_default_heartbeat_slashing_window() -> Weight;
	fn join_service() -> Weight;
	fn leave_service() -> Weight;
	fn validate_payment_amount_pay_once() -> Weight;
	fn process_subscription_payment() -> Weight;
	fn process_event_driven_payment() -> Weight;
	fn process_subscription_payments_on_idle() -> Weight;
	fn trigger_subscription_payment() -> Weight;
}

/// Weights for `pallet_services` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Services::NextBlueprintId` (r:1 w:1)
	/// Proof: `Services::NextBlueprintId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EVM::AccountCodes` (r:3 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Services::Blueprints` (r:0 w:1)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_blueprint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `412`
		//  Estimated: `8827`
		// Minimum execution time: 41_000_000 picoseconds.
		Weight::from_parts(44_000_000, 8827)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	fn pre_register() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(4_000_000, 0)
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Operators` (r:2 w:1)
	/// Proof: `Services::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EVM::AccountCodes` (r:2 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Services::OperatorsProfile` (r:1 w:1)
	/// Proof: `Services::OperatorsProfile` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1061`
		//  Estimated: `7001`
		// Minimum execution time: 38_000_000 picoseconds.
		Weight::from_parts(41_000_000, 7001)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Operators` (r:1 w:1)
	/// Proof: `Services::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::ServiceStatus` (r:1 w:0)
	/// Proof: `Services::ServiceStatus` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EVM::AccountCodes` (r:2 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Services::OperatorsProfile` (r:1 w:1)
	/// Proof: `Services::OperatorsProfile` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn unregister() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `937`
		//  Estimated: `6877`
		// Minimum execution time: 35_000_000 picoseconds.
		Weight::from_parts(40_000_000, 6877)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Operators` (r:1 w:1)
	/// Proof: `Services::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EVM::AccountCodes` (r:2 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn update_rpc_address() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `908`
		//  Estimated: `6848`
		// Minimum execution time: 31_000_000 picoseconds.
		Weight::from_parts(31_000_000, 6848)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:3 w:0)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Operators` (r:3 w:0)
	/// Proof: `Services::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::NextServiceRequestId` (r:1 w:1)
	/// Proof: `Services::NextServiceRequestId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EVM::AccountCodes` (r:2 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Services::ServiceRequests` (r:0 w:1)
	/// Proof: `Services::ServiceRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2112`
		//  Estimated: `10527`
		// Minimum execution time: 62_000_000 picoseconds.
		Weight::from_parts(69_000_000, 10527)
			.saturating_add(T::DbWeight::get().reads(13_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Services::ServiceRequests` (r:1 w:1)
	/// Proof: `Services::ServiceRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Assets::Asset` (r:2 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Operators` (r:1 w:0)
	/// Proof: `Services::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EVM::AccountCodes` (r:2 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn approve() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1927`
		//  Estimated: `7867`
		// Minimum execution time: 57_000_000 picoseconds.
		Weight::from_parts(61_000_000, 7867)
			.saturating_add(T::DbWeight::get().reads(11_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Services::ServiceRequests` (r:1 w:1)
	/// Proof: `Services::ServiceRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Operators` (r:1 w:0)
	/// Proof: `Services::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EVM::AccountCodes` (r:2 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Services::StagingServicePayments` (r:1 w:0)
	/// Proof: `Services::StagingServicePayments` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn reject() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1250`
		//  Estimated: `7190`
		// Minimum execution time: 34_000_000 picoseconds.
		Weight::from_parts(35_000_000, 7190)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Services::Instances` (r:1 w:1)
	/// Proof: `Services::Instances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::CurrentRound` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::CurrentRound` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Services::UnappliedSlashes` (r:1 w:0)
	/// Proof: `Services::UnappliedSlashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::UserServices` (r:1 w:1)
	/// Proof: `Services::UserServices` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EVM::AccountCodes` (r:2 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Services::OperatorsProfile` (r:3 w:3)
	/// Proof: `Services::OperatorsProfile` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::ServiceStatus` (r:0 w:1)
	/// Proof: `Services::ServiceStatus` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn terminate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1572`
		//  Estimated: `9987`
		// Minimum execution time: 55_000_000 picoseconds.
		Weight::from_parts(56_000_000, 9987)
			.saturating_add(T::DbWeight::get().reads(13_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `Services::Instances` (r:1 w:0)
	/// Proof: `Services::Instances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::NextJobCallId` (r:1 w:1)
	/// Proof: `Services::NextJobCallId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EVM::AccountCodes` (r:2 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Services::JobCalls` (r:0 w:1)
	/// Proof: `Services::JobCalls` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn call() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1194`
		//  Estimated: `7134`
		// Minimum execution time: 34_000_000 picoseconds.
		Weight::from_parts(34_000_000, 7134)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:3 w:0)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Operators` (r:3 w:0)
	/// Proof: `Services::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::NextServiceRequestId` (r:1 w:1)
	/// Proof: `Services::NextServiceRequestId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Assets::Asset` (r:2 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EVM::AccountCodes` (r:2 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Services::NextInstanceId` (r:1 w:1)
	/// Proof: `Services::NextInstanceId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Services::OperatorsProfile` (r:3 w:3)
	/// Proof: `Services::OperatorsProfile` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::UserServices` (r:1 w:1)
	/// Proof: `Services::UserServices` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::StagingServicePayments` (r:0 w:1)
	/// Proof: `Services::StagingServicePayments` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Instances` (r:0 w:1)
	/// Proof: `Services::Instances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::ServiceRequests` (r:0 w:1)
	/// Proof: `Services::ServiceRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::ServiceStatus` (r:0 w:1)
	/// Proof: `Services::ServiceStatus` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn request_with_signed_price_quotes() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3145`
		//  Estimated: `11560`
		// Minimum execution time: 290_000_000 picoseconds.
		Weight::from_parts(293_000_000, 11560)
			.saturating_add(T::DbWeight::get().reads(23_u64))
			.saturating_add(T::DbWeight::get().writes(15_u64))
	}
	/// Storage: `Services::JobCalls` (r:1 w:0)
	/// Proof: `Services::JobCalls` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Instances` (r:1 w:0)
	/// Proof: `Services::Instances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Operators` (r:1 w:0)
	/// Proof: `Services::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EVM::AccountCodes` (r:2 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Services::JobResults` (r:0 w:1)
	/// Proof: `Services::JobResults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_result() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1431`
		//  Estimated: `7371`
		// Minimum execution time: 50_000_000 picoseconds.
		Weight::from_parts(54_000_000, 7371)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Services::ServiceStatus` (r:1 w:0)
	/// Proof: `Services::ServiceStatus` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Instances` (r:1 w:0)
	/// Proof: `Services::Instances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Operators` (r:1 w:0)
	/// Proof: `Services::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::ServiceOperatorHeartbeats` (r:1 w:1)
	/// Proof: `Services::ServiceOperatorHeartbeats` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::ServiceHeartbeats` (r:0 w:1)
	/// Proof: `Services::ServiceHeartbeats` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn heartbeat() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `987`
		//  Estimated: `4452`
		// Minimum execution time: 44_000_000 picoseconds.
		Weight::from_parts(45_000_000, 4452)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Services::Instances` (r:1 w:0)
	/// Proof: `Services::Instances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::CurrentRound` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::CurrentRound` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Services::NextUnappliedSlashIndex` (r:1 w:1)
	/// Proof: `Services::NextUnappliedSlashIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Services::UnappliedSlashes` (r:0 w:1)
	/// Proof: `Services::UnappliedSlashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn slash() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1293`
		//  Estimated: `4758`
		// Minimum execution time: 29_000_000 picoseconds.
		Weight::from_parts(30_000_000, 4758)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Services::UnappliedSlashes` (r:1 w:1)
	/// Proof: `Services::UnappliedSlashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Instances` (r:1 w:0)
	/// Proof: `Services::Instances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn dispute() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `935`
		//  Estimated: `4400`
		// Minimum execution time: 23_000_000 picoseconds.
		Weight::from_parts(23_000_000, 4400)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:1)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn update_master_blueprint_service_manager() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `1594`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(6_000_000, 1594)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Services::DefaultHeartbeatThreshold` (r:0 w:1)
	/// Proof: `Services::DefaultHeartbeatThreshold` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn update_default_heartbeat_threshold() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(4_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Services::DefaultHeartbeatInterval` (r:0 w:1)
	/// Proof: `Services::DefaultHeartbeatInterval` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn update_default_heartbeat_interval() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(3_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Services::DefaultSlashingWindow` (r:0 w:1)
	/// Proof: `Services::DefaultSlashingWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn update_default_heartbeat_slashing_window() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(4_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Services::Instances` (r:1 w:1)
	/// Proof: `Services::Instances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Operators` (r:1 w:0)
	/// Proof: `Services::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EVM::AccountCodes` (r:2 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn join_service() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1332`
		//  Estimated: `7272`
		// Minimum execution time: 49_000_000 picoseconds.
		Weight::from_parts(55_000_000, 7272)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Services::Instances` (r:1 w:1)
	/// Proof: `Services::Instances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Operators` (r:1 w:0)
	/// Proof: `Services::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EVM::AccountCodes` (r:2 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn leave_service() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1383`
		//  Estimated: `7323`
		// Minimum execution time: 45_000_000 picoseconds.
		Weight::from_parts(45_000_000, 7323)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn validate_payment_amount_pay_once() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 0_000 picoseconds.
		Weight::from_parts(0, 0)
	}
	/// Storage: `Services::JobSubscriptionBillings` (r:1 w:0)
	/// Proof: `Services::JobSubscriptionBillings` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::UserSubscriptionCount` (r:1 w:1)
	/// Proof: `Services::UserSubscriptionCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn process_subscription_payment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `336`
		//  Estimated: `6196`
		// Minimum execution time: 14_000_000 picoseconds.
		Weight::from_parts(14_000_000, 6196)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Services::Instances` (r:1 w:0)
	/// Proof: `Services::Instances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn process_event_driven_payment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `336`
		//  Estimated: `3801`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 3801)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `Services::SubscriptionProcessingCursor` (r:1 w:1)
	/// Proof: `Services::SubscriptionProcessingCursor` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Services::JobSubscriptionBillings` (r:1 w:0)
	/// Proof: `Services::JobSubscriptionBillings` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn process_subscription_payments_on_idle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `383`
		//  Estimated: `3848`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 3848)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Services::Instances` (r:1 w:0)
	/// Proof: `Services::Instances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::JobSubscriptionBillings` (r:1 w:1)
	/// Proof: `Services::JobSubscriptionBillings` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Rewards::PendingOperatorRewards` (r:4 w:4)
	/// Proof: `Rewards::PendingOperatorRewards` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::OperatorRewardPools` (r:5 w:5)
	/// Proof: `Rewards::OperatorRewardPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn trigger_subscription_payment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1312`
		//  Estimated: `14677`
		// Minimum execution time: 77_000_000 picoseconds.
		Weight::from_parts(78_000_000, 14677)
			.saturating_add(T::DbWeight::get().reads(14_u64))
			.saturating_add(T::DbWeight::get().writes(12_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Services::NextBlueprintId` (r:1 w:1)
	/// Proof: `Services::NextBlueprintId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EVM::AccountCodes` (r:3 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Services::Blueprints` (r:0 w:1)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn create_blueprint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `412`
		//  Estimated: `8827`
		// Minimum execution time: 41_000_000 picoseconds.
		Weight::from_parts(44_000_000, 8827)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	fn pre_register() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(4_000_000, 0)
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Operators` (r:2 w:1)
	/// Proof: `Services::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EVM::AccountCodes` (r:2 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Services::OperatorsProfile` (r:1 w:1)
	/// Proof: `Services::OperatorsProfile` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1061`
		//  Estimated: `7001`
		// Minimum execution time: 38_000_000 picoseconds.
		Weight::from_parts(41_000_000, 7001)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Operators` (r:1 w:1)
	/// Proof: `Services::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::ServiceStatus` (r:1 w:0)
	/// Proof: `Services::ServiceStatus` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EVM::AccountCodes` (r:2 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Services::OperatorsProfile` (r:1 w:1)
	/// Proof: `Services::OperatorsProfile` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn unregister() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `937`
		//  Estimated: `6877`
		// Minimum execution time: 35_000_000 picoseconds.
		Weight::from_parts(40_000_000, 6877)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Operators` (r:1 w:1)
	/// Proof: `Services::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EVM::AccountCodes` (r:2 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn update_rpc_address() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `908`
		//  Estimated: `6848`
		// Minimum execution time: 31_000_000 picoseconds.
		Weight::from_parts(31_000_000, 6848)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:3 w:0)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Operators` (r:3 w:0)
	/// Proof: `Services::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::NextServiceRequestId` (r:1 w:1)
	/// Proof: `Services::NextServiceRequestId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EVM::AccountCodes` (r:2 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Services::ServiceRequests` (r:0 w:1)
	/// Proof: `Services::ServiceRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn request() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2112`
		//  Estimated: `10527`
		// Minimum execution time: 62_000_000 picoseconds.
		Weight::from_parts(69_000_000, 10527)
			.saturating_add(RocksDbWeight::get().reads(13_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Services::ServiceRequests` (r:1 w:1)
	/// Proof: `Services::ServiceRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Assets::Asset` (r:2 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Operators` (r:1 w:0)
	/// Proof: `Services::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EVM::AccountCodes` (r:2 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn approve() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1927`
		//  Estimated: `7867`
		// Minimum execution time: 57_000_000 picoseconds.
		Weight::from_parts(61_000_000, 7867)
			.saturating_add(RocksDbWeight::get().reads(11_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Services::ServiceRequests` (r:1 w:1)
	/// Proof: `Services::ServiceRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Operators` (r:1 w:0)
	/// Proof: `Services::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EVM::AccountCodes` (r:2 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Services::StagingServicePayments` (r:1 w:0)
	/// Proof: `Services::StagingServicePayments` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn reject() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1250`
		//  Estimated: `7190`
		// Minimum execution time: 34_000_000 picoseconds.
		Weight::from_parts(35_000_000, 7190)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Services::Instances` (r:1 w:1)
	/// Proof: `Services::Instances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::CurrentRound` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::CurrentRound` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Services::UnappliedSlashes` (r:1 w:0)
	/// Proof: `Services::UnappliedSlashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::UserServices` (r:1 w:1)
	/// Proof: `Services::UserServices` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EVM::AccountCodes` (r:2 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Services::OperatorsProfile` (r:3 w:3)
	/// Proof: `Services::OperatorsProfile` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::ServiceStatus` (r:0 w:1)
	/// Proof: `Services::ServiceStatus` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn terminate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1572`
		//  Estimated: `9987`
		// Minimum execution time: 55_000_000 picoseconds.
		Weight::from_parts(56_000_000, 9987)
			.saturating_add(RocksDbWeight::get().reads(13_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `Services::Instances` (r:1 w:0)
	/// Proof: `Services::Instances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::NextJobCallId` (r:1 w:1)
	/// Proof: `Services::NextJobCallId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EVM::AccountCodes` (r:2 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Services::JobCalls` (r:0 w:1)
	/// Proof: `Services::JobCalls` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn call() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1194`
		//  Estimated: `7134`
		// Minimum execution time: 34_000_000 picoseconds.
		Weight::from_parts(34_000_000, 7134)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `MultiAssetDelegation::Operators` (r:3 w:0)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Operators` (r:3 w:0)
	/// Proof: `Services::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::NextServiceRequestId` (r:1 w:1)
	/// Proof: `Services::NextServiceRequestId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Assets::Asset` (r:2 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EVM::AccountCodes` (r:2 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Services::NextInstanceId` (r:1 w:1)
	/// Proof: `Services::NextInstanceId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Services::OperatorsProfile` (r:3 w:3)
	/// Proof: `Services::OperatorsProfile` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::UserServices` (r:1 w:1)
	/// Proof: `Services::UserServices` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::StagingServicePayments` (r:0 w:1)
	/// Proof: `Services::StagingServicePayments` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Instances` (r:0 w:1)
	/// Proof: `Services::Instances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::ServiceRequests` (r:0 w:1)
	/// Proof: `Services::ServiceRequests` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::ServiceStatus` (r:0 w:1)
	/// Proof: `Services::ServiceStatus` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn request_with_signed_price_quotes() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3145`
		//  Estimated: `11560`
		// Minimum execution time: 290_000_000 picoseconds.
		Weight::from_parts(293_000_000, 11560)
			.saturating_add(RocksDbWeight::get().reads(23_u64))
			.saturating_add(RocksDbWeight::get().writes(15_u64))
	}
	/// Storage: `Services::JobCalls` (r:1 w:0)
	/// Proof: `Services::JobCalls` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Instances` (r:1 w:0)
	/// Proof: `Services::Instances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Operators` (r:1 w:0)
	/// Proof: `Services::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EVM::AccountCodes` (r:2 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Services::JobResults` (r:0 w:1)
	/// Proof: `Services::JobResults` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_result() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1431`
		//  Estimated: `7371`
		// Minimum execution time: 50_000_000 picoseconds.
		Weight::from_parts(54_000_000, 7371)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Services::ServiceStatus` (r:1 w:0)
	/// Proof: `Services::ServiceStatus` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Instances` (r:1 w:0)
	/// Proof: `Services::Instances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Operators` (r:1 w:0)
	/// Proof: `Services::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::ServiceOperatorHeartbeats` (r:1 w:1)
	/// Proof: `Services::ServiceOperatorHeartbeats` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::ServiceHeartbeats` (r:0 w:1)
	/// Proof: `Services::ServiceHeartbeats` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn heartbeat() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `987`
		//  Estimated: `4452`
		// Minimum execution time: 44_000_000 picoseconds.
		Weight::from_parts(45_000_000, 4452)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Services::Instances` (r:1 w:0)
	/// Proof: `Services::Instances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::Operators` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::CurrentRound` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::CurrentRound` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Services::NextUnappliedSlashIndex` (r:1 w:1)
	/// Proof: `Services::NextUnappliedSlashIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Services::UnappliedSlashes` (r:0 w:1)
	/// Proof: `Services::UnappliedSlashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn slash() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1293`
		//  Estimated: `4758`
		// Minimum execution time: 29_000_000 picoseconds.
		Weight::from_parts(30_000_000, 4758)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Services::UnappliedSlashes` (r:1 w:1)
	/// Proof: `Services::UnappliedSlashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Instances` (r:1 w:0)
	/// Proof: `Services::Instances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn dispute() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `935`
		//  Estimated: `4400`
		// Minimum execution time: 23_000_000 picoseconds.
		Weight::from_parts(23_000_000, 4400)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:1)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn update_master_blueprint_service_manager() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `1594`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(6_000_000, 1594)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Services::DefaultHeartbeatThreshold` (r:0 w:1)
	/// Proof: `Services::DefaultHeartbeatThreshold` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn update_default_heartbeat_threshold() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(4_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Services::DefaultHeartbeatInterval` (r:0 w:1)
	/// Proof: `Services::DefaultHeartbeatInterval` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn update_default_heartbeat_interval() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(3_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Services::DefaultSlashingWindow` (r:0 w:1)
	/// Proof: `Services::DefaultSlashingWindow` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn update_default_heartbeat_slashing_window() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(4_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Services::Instances` (r:1 w:1)
	/// Proof: `Services::Instances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Operators` (r:1 w:0)
	/// Proof: `Services::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EVM::AccountCodes` (r:2 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn join_service() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1332`
		//  Estimated: `7272`
		// Minimum execution time: 49_000_000 picoseconds.
		Weight::from_parts(55_000_000, 7272)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Services::Instances` (r:1 w:1)
	/// Proof: `Services::Instances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Operators` (r:1 w:0)
	/// Proof: `Services::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::MasterBlueprintServiceManagerRevisions` (r:1 w:0)
	/// Proof: `Services::MasterBlueprintServiceManagerRevisions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `BaseFee::BaseFeePerGas` (r:1 w:0)
	/// Proof: `BaseFee::BaseFeePerGas` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `EVM::AccountCodes` (r:2 w:0)
	/// Proof: `EVM::AccountCodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn leave_service() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1383`
		//  Estimated: `7323`
		// Minimum execution time: 45_000_000 picoseconds.
		Weight::from_parts(45_000_000, 7323)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn validate_payment_amount_pay_once() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 0_000 picoseconds.
		Weight::from_parts(0, 0)
	}
	/// Storage: `Services::JobSubscriptionBillings` (r:1 w:0)
	/// Proof: `Services::JobSubscriptionBillings` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::UserSubscriptionCount` (r:1 w:1)
	/// Proof: `Services::UserSubscriptionCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn process_subscription_payment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `336`
		//  Estimated: `6196`
		// Minimum execution time: 14_000_000 picoseconds.
		Weight::from_parts(14_000_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Services::Instances` (r:1 w:0)
	/// Proof: `Services::Instances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn process_event_driven_payment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `336`
		//  Estimated: `3801`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 3801)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	/// Storage: `Services::SubscriptionProcessingCursor` (r:1 w:1)
	/// Proof: `Services::SubscriptionProcessingCursor` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Services::JobSubscriptionBillings` (r:1 w:0)
	/// Proof: `Services::JobSubscriptionBillings` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn process_subscription_payments_on_idle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `383`
		//  Estimated: `3848`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(6_000_000, 3848)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Services::Instances` (r:1 w:0)
	/// Proof: `Services::Instances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::Blueprints` (r:1 w:0)
	/// Proof: `Services::Blueprints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Services::JobSubscriptionBillings` (r:1 w:1)
	/// Proof: `Services::JobSubscriptionBillings` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Rewards::PendingOperatorRewards` (r:4 w:4)
	/// Proof: `Rewards::PendingOperatorRewards` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Rewards::OperatorRewardPools` (r:5 w:5)
	/// Proof: `Rewards::OperatorRewardPools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn trigger_subscription_payment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1312`
		//  Estimated: `14677`
		// Minimum execution time: 77_000_000 picoseconds.
		Weight::from_parts(78_000_000, 14677)
			.saturating_add(RocksDbWeight::get().reads(14_u64))
			.saturating_add(RocksDbWeight::get().writes(12_u64))
	}
}