[package]
name = "tangle-rococo-runtime"
description = "Webb Protocol Tangle Network runtime"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
substrate-wasm-builder = { workspace = true }

[dependencies]
codec = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
hex-literal = { workspace = true, optional = true }
log = { workspace = true }
scale-info = { workspace = true }

# DKG Substrate Dependencies
dkg-runtime-primitives = { workspace = true }
pallet-dkg-metadata = { workspace = true }
pallet-dkg-proposal-handler = { workspace = true }
pallet-dkg-proposals = { workspace = true }
pallet-bridge-registry = { workspace = true }

# Protocol Substrate Dependencies
pallet-asset-registry = { workspace = true }
pallet-ecdsa-claims = { workspace = true }
pallet-hasher = { workspace = true }
pallet-key-storage = { workspace = true }
pallet-linkable-tree = { workspace = true }
pallet-linkable-tree-rpc-runtime-api = { workspace = true }
pallet-mixer = { workspace = true }
pallet-mt = { workspace = true }
pallet-mt-rpc-runtime-api = { workspace = true }
pallet-signature-bridge = { workspace = true }
pallet-token-wrapper = { workspace = true }
pallet-token-wrapper-handler = { workspace = true }
pallet-vanchor = { workspace = true }
pallet-vanchor-handler = { workspace = true }
pallet-vanchor-verifier = { workspace = true }
pallet-verifier = { workspace = true }
webb-primitives = { workspace = true }

orml-benchmarking = { workspace = true, optional = true }
orml-currencies = { workspace = true }
orml-tokens = { workspace = true }
orml-traits = { workspace = true }

# Substrate Dependencies
## Substrate Primitive Dependencies
sp-api = { workspace = true }
sp-arithmetic = { workspace = true }
sp-block-builder = { workspace = true }
sp-consensus-aura = { workspace = true }
sp-core = { workspace = true }
sp-inherents = { workspace = true }
sp-offchain = { workspace = true }
sp-runtime = { workspace = true }
sp-session = { workspace = true }
sp-std = { workspace = true }
sp-transaction-pool = { workspace = true }
sp-version = { workspace = true }

## Substrate FRAME Dependencies
frame-benchmarking = { workspace = true, optional = true }
frame-executive = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
frame-system-benchmarking = { workspace = true, optional = true }
frame-system-rpc-runtime-api = { workspace = true }
sp-application-crypto = { workspace = true }

## Substrate Pallet Dependencies
pallet-aura = { workspace = true }
pallet-authorship = { workspace = true }
pallet-balances = { workspace = true }
pallet-collective = { workspace = true }
pallet-democracy = { workspace = true }
pallet-identity = { workspace = true }
pallet-im-online = { workspace = true }
pallet-indices = { workspace = true }
pallet-preimage = { workspace = true }
pallet-randomness-collective-flip = { workspace = true }
pallet-scheduler = { workspace = true }
pallet-session = { workspace = true }
pallet-sudo = { workspace = true }
pallet-timestamp = { workspace = true }
pallet-transaction-payment = { workspace = true }
pallet-transaction-payment-rpc-runtime-api = { workspace = true }
pallet-treasury = { workspace = true }
pallet-utility = { workspace = true }
pallet-vesting = { workspace = true }

# Cumulus Dependencies
cumulus-pallet-dmp-queue = { workspace = true }
cumulus-pallet-parachain-system = { workspace = true }
cumulus-pallet-xcm = { workspace = true }
cumulus-pallet-xcmp-queue = { workspace = true }
cumulus-primitives-core = { workspace = true }
cumulus-primitives-timestamp = { workspace = true }
cumulus-primitives-utility = { workspace = true }
parachain-info = { workspace = true }

# Polkadot Dependencies
pallet-xcm = { workspace = true }
polkadot-parachain = { workspace = true }
polkadot-runtime-common = { workspace = true }
xcm = { workspace = true }
xcm-builder = { workspace = true }
xcm-executor = { workspace = true }

# Nimbus Dependencies
nimbus-primitives = { workspace = true }
pallet-aura-style-filter = { workspace = true }
pallet-author-inherent = { workspace = true }

# Local dependencies
pallet-parachain-staking = { workspace = true }
pallet-transaction-pause = { workspace = true }
tangle-primitives = { workspace = true }

[features]
default = ["std"]
std = [
  "codec/std",
  "scale-info/std",
  "log/std",
  "sp-api/std",
  "sp-std/std",
  "sp-core/std",
  "sp-runtime/std",
  "sp-version/std",
  "sp-offchain/std",
  "sp-session/std",
  "sp-block-builder/std",
  "sp-transaction-pool/std",
  "sp-inherents/std",
  "frame-support/std",
  "frame-executive/std",
  "frame-system/std",
  "frame-benchmarking/std",
  "pallet-balances/std",
  "pallet-randomness-collective-flip/std",
  "pallet-timestamp/std",
  "pallet-sudo/std",
  "pallet-transaction-payment/std",
  "parachain-info/std",
  "cumulus-pallet-parachain-system/std",
  "cumulus-pallet-dmp-queue/std",
  "cumulus-pallet-xcmp-queue/std",
  "cumulus-pallet-xcm/std",
  "cumulus-primitives-core/std",
  "cumulus-primitives-timestamp/std",
  "cumulus-primitives-utility/std",
  "xcm/std",
  "xcm-builder/std",
  "xcm-executor/std",
  "pallet-xcm/std",
  "polkadot-parachain/std",
  "polkadot-runtime-common/std",
  "pallet-aura/std",
  "sp-consensus-aura/std",
  "pallet-authorship/std",
  "pallet-session/std",
  "pallet-im-online/std",
  "pallet-indices/std",
  "pallet-treasury/std",
  "pallet-identity/std",
  "pallet-vesting/std",
  "pallet-utility/std",
  "pallet-democracy/std",
  "pallet-scheduler/std",
  "pallet-preimage/std",
  "orml-benchmarking/std",
  "sp-arithmetic/std",
  "sp-application-crypto/std",

  # DKG
  "pallet-dkg-metadata/std",
  "dkg-runtime-primitives/std",
  "pallet-dkg-proposals/std",
  "pallet-dkg-proposal-handler/std",
  "pallet-bridge-registry/std",

  # Protocol Substrate
  "webb-primitives/std",
  "pallet-hasher/std",
  "pallet-mt/std",
  "pallet-linkable-tree/std",
  "pallet-mt-rpc-runtime-api/std",
  "pallet-linkable-tree-rpc-runtime-api/std",
  "pallet-verifier/std",
  "orml-currencies/std",
  "orml-tokens/std",
  "orml-traits/std",
  "pallet-asset-registry/std",
  "pallet-signature-bridge/std",
  "pallet-mixer/std",
  "pallet-token-wrapper/std",
  "pallet-token-wrapper-handler/std",
  "orml-benchmarking/std",
  "pallet-vanchor/std",
  "pallet-vanchor-handler/std",
  "pallet-vanchor-verifier/std",

  'nimbus-primitives/std',
  'pallet-aura-style-filter/std',
  'pallet-author-inherent/std',

  # local
  "pallet-ecdsa-claims/std",
  "pallet-parachain-staking/std",
  "tangle-primitives/std",
  "pallet-transaction-pause/std",
]
runtime-benchmarks = [
  "hex-literal",
  "frame-benchmarking",
  "frame-system-benchmarking",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "pallet-balances/runtime-benchmarks",
  "pallet-timestamp/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
  "pallet-xcm/runtime-benchmarks",
  "xcm-builder/runtime-benchmarks",
  "pallet-collective/runtime-benchmarks",

  # protocol-substrate deps
  "pallet-signature-bridge/runtime-benchmarks",
  "pallet-mt/runtime-benchmarks",
  "pallet-mixer/runtime-benchmarks",
  "pallet-linkable-tree/runtime-benchmarks",
  "pallet-hasher/runtime-benchmarks",
  "pallet-verifier/runtime-benchmarks",
  "pallet-asset-registry/runtime-benchmarks",
  "pallet-token-wrapper/runtime-benchmarks",

  # dkg deps
  "pallet-dkg-metadata/runtime-benchmarks",
  "pallet-dkg-proposals/runtime-benchmarks",
  "pallet-dkg-proposal-handler/runtime-benchmarks",

  # local deps
  "pallet-parachain-staking/runtime-benchmarks",
]
try-runtime = [
  "frame-executive/try-runtime",
  "pallet-parachain-staking/try-runtime",
]
