[package]
name = "precompile-utils-macro"
version = "0.1.0"
authors = { workspace = true }
edition = "2021"
description = ""

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/tests.rs"

[dependencies]
case = "1.0"
num_enum = { workspace = true }
proc-macro2 = "1.0"
quote = "1.0"
sha3 = "0.10"
syn = { workspace = true, features = ["extra-traits", "fold", "full", "visit"] }

[dev-dependencies]
macrotest = "1.0.13"
trybuild = "1.0"

precompile-utils = { path = "../", features = ["testing"] }

fp-evm = { workspace = true }
frame-support = { workspace = true }
sp-core = { workspace = true }
sp-std = { workspace = true }
