[package]
name = "pallet-evm-precompile-multi-asset-delegation-fuzzer"
version = "2.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage.workspace = true
repository.workspace = true
description = "Fuzzer for pallet-multi-asset-delegation precompile"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
honggfuzz = { workspace = true }


pallet-multi-asset-delegation = { workspace = true, features = ["fuzzing"], default-features = true }
pallet-evm-precompile-multi-asset-delegation = { features = ["fuzzing"], workspace = true, default-features = true }
sp-core = { workspace = true }
frame-system = { workspace = true, default-features = true }
frame-support = { workspace = true, default-features = true }

fp-evm = { workspace = true }
precompile-utils = { workspace = true, features = ["std", "testing"] }
pallet-evm = { workspace = true, features = ["forbid-evm-reentrancy"] }

sp-runtime = { workspace = true, default-features = true }
sp-io = { workspace = true, default-features = true }
sp-tracing = { workspace = true, default-features = true }

rand = { features = ["small_rng"], workspace = true, default-features = true }
log = { workspace = true, default-features = true }

[[bin]]
name = "mad-precompile-fuzzer"
path = "call.rs"
