// This file is part of Tangle.
// Copyright (C) 2022-2025 Tangle Foundation.
//
// Tangle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Tangle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Tangle.  If not, see <http://www.gnu.org/licenses/>.


//! Autogenerated weights for `pallet_credits`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 42.0.1
//! DATE: 2025-11-06, STEPS: `10`, REPEAT: `2`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `192.168.1.138`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/tangle
// benchmark
// pallet
// --chain=dev
// --wasm-execution=compiled
// --pallet=pallet_credits
// --extrinsic=*
// --steps=10
// --repeat=2
// --template=./.maintain/frame-weights-template.hbs
// --output=./pallets/credits/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_credits`.
pub trait WeightInfo {
	fn burn() -> Weight;
	fn claim_credits() -> Weight;
	fn set_stake_tiers() -> Weight;
	fn claim_credits_with_asset() -> Weight;
	fn set_asset_stake_tiers() -> Weight;
}

/// Weights for `pallet_credits` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Credits::LastRewardUpdateBlock` (r:1 w:1)
	/// Proof: `Credits::LastRewardUpdateBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `480`
		//  Estimated: `6196`
		// Minimum execution time: 34_000_000 picoseconds.
		Weight::from_parts(36_000_000, 6196)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `Credits::LastRewardUpdateBlock` (r:1 w:1)
	/// Proof: `Credits::LastRewardUpdateBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Credits::StoredStakeTiers` (r:1 w:0)
	/// Proof: `Credits::StoredStakeTiers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn claim_credits() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `478`
		//  Estimated: `3943`
		// Minimum execution time: 13_000_000 picoseconds.
		Weight::from_parts(13_000_000, 3943)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Credits::StoredStakeTiers` (r:0 w:1)
	/// Proof: `Credits::StoredStakeTiers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_stake_tiers() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Credits::LastRewardUpdateBlock` (r:1 w:1)
	/// Proof: `Credits::LastRewardUpdateBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Credits::AssetStakeTiers` (r:1 w:0)
	/// Proof: `Credits::AssetStakeTiers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn claim_credits_with_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `522`
		//  Estimated: `3987`
		// Minimum execution time: 13_000_000 picoseconds.
		Weight::from_parts(14_000_000, 3987)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Credits::AssetStakeTiers` (r:0 w:1)
	/// Proof: `Credits::AssetStakeTiers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_asset_stake_tiers() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Credits::LastRewardUpdateBlock` (r:1 w:1)
	/// Proof: `Credits::LastRewardUpdateBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `480`
		//  Estimated: `6196`
		// Minimum execution time: 34_000_000 picoseconds.
		Weight::from_parts(36_000_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `Credits::LastRewardUpdateBlock` (r:1 w:1)
	/// Proof: `Credits::LastRewardUpdateBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Credits::StoredStakeTiers` (r:1 w:0)
	/// Proof: `Credits::StoredStakeTiers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn claim_credits() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `478`
		//  Estimated: `3943`
		// Minimum execution time: 13_000_000 picoseconds.
		Weight::from_parts(13_000_000, 3943)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Credits::StoredStakeTiers` (r:0 w:1)
	/// Proof: `Credits::StoredStakeTiers` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_stake_tiers() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Credits::LastRewardUpdateBlock` (r:1 w:1)
	/// Proof: `Credits::LastRewardUpdateBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MultiAssetDelegation::Delegators` (r:1 w:0)
	/// Proof: `MultiAssetDelegation::Delegators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Credits::AssetStakeTiers` (r:1 w:0)
	/// Proof: `Credits::AssetStakeTiers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn claim_credits_with_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `522`
		//  Estimated: `3987`
		// Minimum execution time: 13_000_000 picoseconds.
		Weight::from_parts(14_000_000, 3987)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Credits::AssetStakeTiers` (r:0 w:1)
	/// Proof: `Credits::AssetStakeTiers` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_asset_stake_tiers() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}