name: Auto review PRs

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  auto-review:
    if: github.event.pull_request.draft == false
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Auto review PR
        uses: anthropics/claude-code-action@beta
        with:
          direct_prompt: |
            Please review this PR. Look at the changes and provide thoughtful feedback on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security implications (for the substrate blockchain)
            - Documentation updates if needed

            Be constructive and specific in your feedback. Give inline comments where applicable.
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          allowed_tools: "mcp__github__add_pull_request_review_comment"
