name: Publish Binary

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install toolchain
      id: toolchain
      uses: actions-rs/toolchain@master
      with:
        profile: minimal
        toolchain: nightly
        target: wasm32-unknown-unknown

    - name: Rust Cache
      uses: Swatinem/rust-cache@v1.3.0

    - name: Install Protobuf
      run: sudo apt-get install protobuf-compiler

    - name: Build binary
      run: cargo build --release -p tangle-standalone --locked
    
    - name: Upload regular binary to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/tangle-standalone
        asset_name: tangle-standalone-linux-amd64
        tag: ${{ github.ref }}
        overwrite: true

    - name: Build binary with txpool
      run: cargo build --release -p tangle-standalone --locked --features txpool
    
    - name: Upload txpool binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/tangle-standalone
        asset_name: tangle-standalone-txpool-linux-amd64
        tag: ${{ github.ref }}
        overwrite: true

    - name: Build binary with relayer
      run: cargo build --release -p tangle-standalone --locked --features relayer
    
    - name: Upload relayer binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/tangle-standalone
        asset_name: tangle-standalone-relayer-linux-amd64
        tag: ${{ github.ref }}
        overwrite: true