name: Srtool Wasm Publish

on:
  workflow_dispatch:

  push:
    tags: ["v*.*.*"]

jobs:
  srtool:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chain: ["testnet", "mainnet"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout srtool
        uses: actions/checkout@v4
        with:
          repository: paritytech/srtool
          path: srtool-repo

      - name: Get latest Rust version
        id: rust-version
        run: |
          # Get the latest stable Rust version
          LATEST_RUST=$(curl -s https://forge.rust-lang.org/channel-releases.html | grep -oP 'stable.*?(\d+\.\d+\.\d+)' | head -1 | grep -oP '\d+\.\d+\.\d+')
          echo "version=$LATEST_RUST" >> $GITHUB_OUTPUT
          echo "Latest Rust version: $LATEST_RUST"

      - name: Build srtool Docker image
        run: |
          cd srtool-repo
          RUSTC_VERSION=${{ steps.rust-version.outputs.version }}
          echo "Building srtool with Rust $RUSTC_VERSION"
          docker build --build-arg RUSTC_VERSION=$RUSTC_VERSION -t local-srtool:latest .
      
      - name: Run Srtool build
        id: srtool_build
        shell: bash
        run: |
          git config --global --add safe.directory /build

          if [ "${{ matrix.chain }}" == "mainnet" ]; then
            PACKAGE="tangle-runtime"
          else
            PACKAGE="tangle-testnet-runtime"
          fi

          docker run --user $(id -u):$(id -g) \
            -e PACKAGE=$PACKAGE \
            -e RUNTIME_DIR=runtime/${{ matrix.chain }} \
            -e BUILD_OPTS="--features on-chain-release-build" \
            -v $(pwd):/build \
            local-srtool:latest build

      - name: Summary
        run: |
          if [ "${{ matrix.chain }}" == "mainnet" ]; then
            WASM_PATH="runtime/mainnet/target/srtool/release/wbuild/tangle-runtime/tangle_runtime.compact.wasm"
            WASM_COMPRESSED_PATH="runtime/mainnet/target/srtool/release/wbuild/tangle-runtime/tangle_runtime.compact.compressed.wasm"
          else
            WASM_PATH="runtime/testnet/target/srtool/release/wbuild/tangle-testnet-runtime/tangle_testnet_runtime.compact.wasm"
            WASM_COMPRESSED_PATH="runtime/testnet/target/srtool/release/wbuild/tangle-testnet-runtime/tangle_testnet_runtime.compact.compressed.wasm"
          fi

          echo "wasm=$WASM_PATH" >> "$GITHUB_ENV"
          echo "wasm_compressed=$WASM_COMPRESSED_PATH" >> "$GITHUB_ENV"

          echo "{\"wasm\":\"$WASM_PATH\",\"wasm_compressed\":\"$WASM_COMPRESSED_PATH\"}" > ${{ matrix.chain }}-srtool-digest.json
          cat ${{ matrix.chain }}-srtool-digest.json
          echo "Runtime location: $WASM_PATH"

          echo Summary:
          echo - wasm: $WASM_PATH
          echo - wasm_compressed: $WASM_COMPRESSED_PATH

      - name: Upload ${{ matrix.chain }} wasm to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.wasm_compressed }}
          asset_name: tangle-${{ matrix.chain }}-srtool-compact.compressed.wasm
          tag: ${{ github.ref }}
          overwrite: true