name: Publish Binary

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release -p tangle-standalone --locked
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/tangle-standalone
        asset_name: tangle-standalone-linux-amd64
        tag: ${{ github.ref }}
        overwrite: true
        body: "Tangle Standalone Binary"