name: Publish Types

# If changes are made to the types/src/** files
# Issue a new release to npm for the types package.
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'types/src/interfaces/**'
      - 'types/src/index.ts'

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      # Configure SSH with private SSH key
      - name: Attach SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}

      - name: Configure Github Actions user
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"

      - name: Initialize the NPM config
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install npm dependencies
        run: |
          cd types
          yarn install

      - name: Publish the package
        run: |
          cd types
          yarn publish-types --ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
