[package]
name = "tangle-parachain"
build = "build.rs"
description = "Webb Protocol Tangle Parachain Network"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
substrate-build-script-utils = { workspace = true }

[[bin]]
name = "tangle-parachain"

[features]
default = ["std"]
std = ["serde"]
runtime-benchmarks = ["tangle-rococo-runtime/runtime-benchmarks"]
rococo-native = [
  "polkadot-cli/rococo-native",
]
try-runtime = ["tangle-rococo-runtime/try-runtime"]

[dependencies]
async-trait = { workspace = true }
clap = { workspace = true }
codec = { package = "parity-scale-codec", version = "3" }
futures = { workspace = true }
hex-literal = { workspace = true }
log = { workspace = true }
serde = { workspace = true, optional=true }

# RPC related Dependencies
jsonrpsee = { workspace = true }

# Local Dependencies
dkg-gadget = { workspace = true }
dkg-primitives = { workspace = true }
dkg-runtime-primitives = { workspace = true }
pallet-bridge-registry = { workspace = true }
tangle-rococo-runtime = { workspace = true }

# Substrate Dependencies
frame-benchmarking = { workspace = true }
frame-benchmarking-cli = { workspace = true }
frame-rpc-system = { workspace = true }
pallet-transaction-payment-rpc = { workspace = true }
substrate-prometheus-endpoint = { workspace = true }

## Substrate Client Dependencies
sc-basic-authorship = { workspace = true }
sc-chain-spec = { workspace = true }
sc-client-db = { workspace = true }
sc-cli = { workspace = true }
sc-client-api = { workspace = true }
sc-consensus = { workspace = true }
sc-executor = { workspace = true }
sc-network = { workspace = true }
sc-rpc = { workspace = true }
sc-service = { workspace = true }
sc-sysinfo = { workspace = true }
sc-telemetry = { workspace = true }
sc-tracing = { workspace = true }
sc-network-common = { workspace = true }
sc-transaction-pool = { workspace = true }
sc-transaction-pool-api = { workspace = true }
try-runtime-cli = { workspace = true }
## Substrate Primitive Dependencies
sc-consensus-aura = { workspace = true }
sc-consensus-slots = { workspace = true }
sp-api = { workspace = true }
sp-block-builder = { workspace = true }
sp-blockchain = { workspace = true }
sp-consensus = { workspace = true }
sp-consensus-aura = { workspace = true }
sp-core = { workspace = true }
sp-inherents = { workspace = true }
sp-keystore = { workspace = true }
sp-offchain = { workspace = true }
sp-runtime = { workspace = true }
sp-session = { workspace = true }
sp-timestamp = { workspace = true }
sp-transaction-pool = { workspace = true }

# Cumulus dependencies
cumulus-client-cli = { workspace = true }
cumulus-client-consensus-aura = { workspace = true }
cumulus-client-consensus-common = { workspace = true }
cumulus-client-network = { workspace = true }
cumulus-client-service = { workspace = true }
cumulus-primitives-core = { workspace = true }
cumulus-primitives-parachain-inherent = { workspace = true }
cumulus-relay-chain-interface = { workspace = true }

# Polkadot dependencies
polkadot-cli = { workspace = true }
polkadot-primitives = { workspace = true }
polkadot-service = { workspace = true }

# Nimbus dependencies
nimbus-consensus = { workspace = true }
nimbus-primitives = { workspace = true }
